### ISSUE TITLE
`CHANGELOG.md` bump failed for branch with valid changelog?

### ISSUE THREAD

**Issue by Ocramius** [laminas/automatic-releases#57]
### Bug Report

See https://github.com/Ocramius/PackageVersions/actions/runs/213423994

|    Q        |   A
|------------ | ------
| Version(s)  | 1.2.4

Didn't manage to investigate further, but changelog commit seemed to fail due to no generated diff (by the changelog bump tool)

**Comment by Ocramius** [comment]
More reproducers: https://github.com/Ocramius/PackageVersions/runs/997860158?check_suite_focus=true

Possibly my `CHANGELOG.md` being non-standard? Will probably consider dropping it completely, instead of pursuing (not important for me, given the release notes include the changelog anyway)

**Comment by weierophinney** [comment]
One way to check your format is to use keep-a-changelog (we have a PHAR if that makes it easier for you to consume; check the releases pages), and run `keep-a-changelog version:list`; if it finds your versions, then try a `keep-a-changelog version:show {version}` and see if it can dump the contents. If either of those operations fail, then it's definitely the formatting that's the culprit.

**Comment by weierophinney** [comment]
Is this resolved with the latest releases, @Ocramius ?

**Comment by Ocramius** [comment]
Haven't tried it yet - no changes in downstream happened for now

**Comment by kpicaza** [comment]
I have the same issue trying the package, in my case the issue was the format of the release version title: 

Normally I use [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator), that generates the release version titles In the following format:

```
## [0.0.3](https://github.com/kpicaza/laminas-component-installer-test/tree/0.0.3) (2020-09-05)
```
Having the described error

![image](https://user-images.githubusercontent.com/1093654/92304369-9fd97300-ef7d-11ea-860f-454e979ae535.png)


Using the same format as https://keepachangelog.com/en/1.0.0/ example solves the issue.
```
## [0.0.3] - 2020-09-05
```
![image](https://user-images.githubusercontent.com/1093654/92304388-ceefe480-ef7d-11ea-819e-ef7dee449592.png)

I'll expect it can help, thanks for your great work. ;-D

**Comment by ramsey** [comment]
I think #73 fixes this. I'm fairly certain this is because phly/keep-a-changelog was failing to parse the content of `CHANGELOG.md`.

**Comment by Ocramius** [comment]
Closing here: please report again if it occurs after `1.8.0`

**Comment by ramsey** [comment]
I just tested this again on [ramsey/devtools](https://github.com/ramsey/devtools), and it worked!

The only hiccup I ran into was with protected branches; it was unable to push to a protected branch during the "Release" step. I turned off the protected branches, and ran it again, and it all went smoothly.
