### ISSUE TITLE
Add descriptions to automatically created milestones

### ISSUE THREAD

**Issue by geerteltink** [laminas/automatic-releases#61]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Add descriptions to automatically created milestones to clarify what they are for.

```
# 2.12.4
next 2.12.x bug fix release (patch)

# 2.13.0
next feature release (minor)

# 3.0.0
next backward compatibility break release (major)
```

**Comment by weierophinney** [comment]
I left a comment in the #contributors channel of the Slack, but I'm going to put it here as well, as I'd like to have a record.

Are the milestones for _users_, or _maintainers_? The reason I ask is because:

- Users cannot assign to a milestone.
- Maintainers assign to milestones to know "when is this release done?"

I could see that changing if we want to use milestones to link to users "here is what is coming next". But even then, we'll likely link to a specific milestone, and, generally speaking, the description text gets lost in:

- The milestone name
- The progress bar
- The list of issues/PRs associated with it

See this one as an example:

- https://github.com/laminas/automatic-releases/milestone/11

I don't even miss the description in there, because there's so much else present.

I guess I'm not sure that we need descriptions at all when they refer to a version. We can link to semver.org if they want to understand what is next. And we could end up with a lot of "next bug fix release" entries that make things MORE confusing for users (unless they also note "in the X.Y series", as you note in the issue summary). When we look at _closed_ milestones, these descriptions are also a bit weird as they refer to "next", but they're now _closed_, because they were either _released_ or _abandoned_.

I think the version name, by itself, should be enough; beyond that, look at the issues assigned to it.

**Comment by weierophinney** [comment]
After some discussion with @froschdesign , I think the main point of contention I have is usage of the word "next". The usage of the words "patch", "minor", and "major" as parentheticals is good as it helps educate users about semver terminology.

I think just having:

- "2.12.x bugfix release (patch)"
- "Feature release (minor)"
- "Backwards incompatible release (major)"

would work fine.
